### ISSUE TITLE
Error - Connection timed out

### ISSUE THREAD

**Issue by kacskrz** [mezutelni/twrp-installer-xiaomi#1]
Przy próbie modyfikacji com.miui.home komunikat jak niżej. Wygląda na to jakby serwer nie działał:
```Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./XET.py", line 546, in <module>
    menu()
  File "./XET.py", line 508, in menu
    sTweaksMenu()
  File "./XET.py", line 455, in sTweaksMenu
    comMiuiHome()
  File "./XET.py", line 131, in comMiuiHome
    urllib.request.urlretrieve('http://80.211.196.53/home.file', resPath+'com.miui.home')
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by mezutelni** [comment]
Dokładnie tak jest, jeszcze dziś to zweryfikuję

01.12.2017 20:12 "Orjon" <notifications@github.com> napisał(a):

**Comment by kacskrz** [comment]
Dzisiaj sprawdziłem update który wysłałeś, nadal nie trybi, tym razem coś takiego - zakładam że coś po mojej stronie. Global Beta 7.12.21, Redmi 4A.
![zrzut ekranu 102](https://user-images.githubusercontent.com/34076548/34322523-6ea6e32a-e829-11e7-958c-e64be9e1da4c.png)

**Comment by mezutelni** [comment]
Jesteś w recovery? 
podeślij mi cat /etc/fstab
  (przez adb komenda 'adb shell "cat /etc/fstab"')

**Comment by kacskrz** [comment]
Robiłem z poziomu telefonu, nie TWRP.
Teraz mi-recovery mam, już podsyłam (poziom z telefonu):
![zrzut ekranu 116](https://user-images.githubusercontent.com/34076548/34640281-12de1104-f2f0-11e7-838c-449a2591cfc3.png)

**Comment by mezutelni** [comment]
Jeśli możesz wejść w twrp (wystarczy fastboot boot) i sprawdzić "adb shell mount"

**Comment by kacskrz** [comment]
Proszę cię bardzo.
![przechwytywanie](https://user-images.githubusercontent.com/34076548/34640389-f1d6ad2a-f2f1-11e7-970b-0a9993209b9c.PNG)

**Comment by mezutelni** [comment]
Nie wiem czy to kwestia apki na telefon, ale nic nie wysłałeś ;)

**Comment by kacskrz** [comment]
Ja u siebie widzę wszystko ;-) Podeślę ci na MIUIPolska.

**Comment by kacskrz** [comment]
Ok, zrobiłem tak:
adb shell "mount /system" wywalał błąd w normalnym trybie, odpaliłem tel w TWRP, gdzie zadziałało.
Odpaliłem XET.py, wybrałem instalację com.miui.home i poszło. Wszystko działa. :)
